# Site settings
title: Island Roots
email: nicoledominguez+islandroots@me.com
description: Getting back to your roots one locally sourced produce box at a time.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://islandrootsfoods.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Custom settings
permalink: /blog/:title.html
